const Noodles = [
  {
    id: 1,
    image: "/ramen.jpg",
    logo: "/logo-pizza.png",
    Name: "fish Noodles",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 2,
    image: "/paperoni.jpeg",
    logo: "/logo-pizza.png",
    Name: "peperoni pizza",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 3,
    image: "/beefNoodles.jpeg",
    logo: "/logo-pizza.png",
    Name: "noodles with beef",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 4,
    image: "/paperoni2.jpeg",
    logo: "/logo-pizza.png",
    Name: "peperoni pizza",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 5,
    image: "/eggNoodles.jpeg",
    logo: "/logo-pizza.png",
    Name: "egg & beef noodles",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 6,
    image: "/paperoni2.jpeg",
    logo: "/logo-pizza.png",
    Name: "peperoni pizza",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 7,
    image: "/spicyRamen.jpeg",
    logo: "/logo-pizza.png",
    Name: "spicy ramen",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 8,
    image: "/paperoni2.jpeg",
    logo: "/logo-pizza.png",
    Name: "peperoni pizza",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 9,
    image: "/eggNoodles2.jpeg",
    logo: "/logo-pizza.png",
    Name: "egg noodles",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 10,
    image: "/ramen.jpg",
    Name: "fish Noodles",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 11,
    image: "/paperoni2.jpeg",
    Name: "noodles soup",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 12,
    image: "/beefNoodles.jpeg",
    logo: "/logo-pizza.png",
    Name: "noodles with beef",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 13,
    image: "/eggNoodles.jpeg",
    logo: "/logo-pizza.png",
    Name: "paperoni pizza",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 14,
    image: "/beefNoodles.jpeg",
    logo: "/logo-pizza.png",
    Name: "noodles with beef",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 15,
    image: "/paperoni.jpeg",
    logo: "/logo-pizza.png",
    Name: "peperoni pizza",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
  {
    id: 16,
    image: "/eggNoodles.jpeg",
    logo: "/logo-pizza.png",
    Name: "egg & beef noodles",
    price: "$12.00",
    rating: 4.5,
    rates: "(34)",
  },
];

export default Noodles;
