const TopFoods = [
  {
    id: 1,
    image: "/soup.webp",
    logo: "/mcdonalds.webp",
    Name: "Shrimp Soup",
    price: "$14.00",
    rating: 4.5,
    rates: "(300)",
  },
  {
    id: 2,
    image: "/Buriyani.jpg",
    logo: "/burgerKing.webp",
    Name: "chicken buriyani",
    price: "$20.00",
    rating: 4.5,
    rates: "(270)",
  },
  {
    id: 3,
    image: "/pasta.jpg",
    logo: "/logo-pizza.png",
    Name: "sausage pasta",
    price: "$15.00",
    rating: 4.5,
    rates: "(250)",
  },
  {
    id: 4,
    image: "/ramen.jpg",
    logo: "/mcdonalds.webp",
    Name: "chicken ramen",
    price: "$8.00",
    rating: 4.5,
    rates: "(226)",
  },
  {
    id: 5,
    image: "/potatoSalad.jpg",
    logo: "/logo-arbys.png",
    Name: "mashed potato salad ",
    price: "$12.00",
    rating: 4.5,
    rates: "(2000",
  },
  {
    id: 6,
    image: "/fish.jpg",
    logo: "/mcdonalds.webp",
    Name: "fish something",
    price: "$4.00",
    rating: 4.5,
    rates: "(199)",
  },
  {
    id: 7,
    image: "/burito.jpg",
    logo: "/burgerKing.webp",
    Name: "burrito",
    price: "$6.00",
    rating: 4.5,
    rates: "(160)",
  },
  {
    id: 8,
    image: "/cupCake.jpg",
    logo: "/logo-arbys.png",
    Name: "cup cake",
    price: "$2.00",
    rating: 4.5,
    rates: "(150)",
  },
  {
    id: 9,
    image: "/cupCake.jpg",
    logo: "/logo-arbys.png",
    Name: "cup cake",
    price: "$2.00",
    rating: 4.5,
    rates: "(150)",
  },
  {
    id: 10,
    image: "/cupCake.jpg",
    logo: "/logo-arbys.png",
    Name: "cup cake",
    price: "$2.00",
    rating: 4.5,
    rates: "(150)",
  },
  {
    id: 11,
    image: "/cupCake.jpg",
    logo: "/logo-arbys.png",
    Name: "cup cake",
    price: "$2.00",
    rating: 4.5,
    rates: "(150)",
  },
  {
    id: 12,
    image: "/cupCake.jpg",
    logo: "/logo-arbys.png",
    Name: "cup cake",
    price: "$2.00",
    rating: 4.5,
    rates: "(150)",
  },
];

export default TopFoods;
